steps:
  # Build the Docker image from the Dockerfile in the repository
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/directed-bongo-401118/assign2:$SHORT_SHA', '.']

  # Push the built image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/directed-bongo-401118/assign2:$SHORT_SHA']

  # Update the Compute Engine instance to use the new image
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['compute', 'instances', 'update-container', 'kumar-instance',
           '--zone', 'us-central1-a',
           '--container-image', 'gcr.io/directed-bongo-401118/assign2:$SHORT_SHA']
